title:              Lauren ipsum
email:              
description:        Where rough drafts are published
author:             Lauren Pritchett
url:                "https://hilgspritch.github.io"

# Social Profiles
twitter_username:   hilgspritch
github_username:    hilgspritch
#facebook_username:  StartBootstrap
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


#authors:
  # hilgspritch:
  #   name: Lauren Pritchett
  #   bio: < Add one >
  #   external-image: false
  #   picture: < path to image >
  #   twitter: hilgspritch
